{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "voice-workflow.namespace" . }}
  labels:
    {{- include "voice-workflow.labels" . | nindent 4 }}
{{- end }}

