apiVersion: v2
name: voice-workflow
description: End-to-End Hindi Voice-to-Voice Workflow
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: riva-server
    version: 2.14.0
    repository: https://helm.ngc.nvidia.com/nvidia/riva/charts
    condition: riva.enabled
